In [1]:
import os
import numpy as np
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv
from cleanco.clean import custom_basename
from cleanco.clean import prepare_default_terms
from kagglehub import dataset_download
load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')
client = OpenAI(api_key = api_key)

c:\Users\ccrea\miniconda3\envs\DELAY-finance-base\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
datadir = os.path.join('..', 'stock-market-dataset')
fn = os.path.join(datadir, 'health_stocks_events.csv')
events = pd.read_csv(fn, index_col = 0, parse_dates = True)

## Load FDA product recalls (class I)

In [3]:
pth = dataset_download('mexwell/fda-product-recalls')
fn = os.path.join(pth, 'fda_product_recalls.csv')
recalls = pd.read_csv(fn, parse_dates = ['center_classification_date'])
msk_med = recalls.product_type.isin(['Drugs', 'Devices', 'Biologics'])
msk_c1 = (recalls.event_classification == 'Class I')
recalls_medc1 = recalls.loc[msk_med & msk_c1]; recalls_medc1

,fei_number,recalling_firm_name,product_type,product_classification,status,distribution_pattern,recalling_firm_city,recalling_firm_state,recalling_firm_country,center_classification_date,reason_for_recall,product_description,event_id,event_classification,product_id,center,recall_details
26,2.936999e+06,Covidien,Devices,Class I,Ongoing,Worldwide - US Nationwide distribution includi...,Boulder,Colorado,United States,2023-04-19,"A manufacturing error, resulted in a less than...",Shiley Adult Flexible Tracheostomy Tube with T...,91943,Class I,199257,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
157,3.014732e+09,"Fresenius Kabi USA, LLC",Devices,Class I,Ongoing,"Domestic: CA, CO, NJ, WI, & UT. No foreign dis...",North Andover,Massachusetts,United States,2023-04-11,Fluid ingress that can cause a loss of electri...,"Ivenix Infusion System (IIS), Large Volume Pum...",91783,Class I,198841,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
185,3.002803e+09,"Abbott Diabetes Care, Inc.",Devices,Class I,Ongoing,U.S. Nationwide.,Alameda,California,United States,2023-04-06,Lithium-ion batteries in glucose monitoring sy...,"FreeStyle Libre Reader, REF: 71525-01, 71701-0...",91756,Class I,198772,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
186,3.002803e+09,"Abbott Diabetes Care, Inc.",Devices,Class I,Ongoing,U.S. Nationwide.,Alameda,California,United States,2023-04-06,Lithium-ion batteries in glucose monitoring sy...,"FreeStyle Libre Reader, REF: 71936-01, 71937-0...",91756,Class I,198773,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
187,3.002803e+09,"Abbott Diabetes Care, Inc.",Devices,Class I,Ongoing,U.S. Nationwide.,Alameda,California,United States,2023-04-06,Lithium-ion batteries in glucose monitoring sy...,"FreeStyle Libre Reader, REF: 71951-01, 71952-0...",91756,Class I,198813,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82896,1.039215e+06,Nidek Medical Products Inc,Devices,Class I,Terminated,Worldwide Distribution-USA (nationwide) and th...,Birmingham,Alabama,United States,2012-06-19,Capacitor failure may result in a fire hazard ...,"NIDEK Medical MARK5 NUVO / M5C5, 115 V ~60Hz -...",61843,Class I,109227,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
82908,1.641527e+06,"Physicians Total Care, Inc",Drugs,Class I,Terminated,FL,Tulsa,Oklahoma,United States,2012-06-18,Labeling: Label mix-up; Bottles labeled to con...,"Morphine Sulfate Extended Release tablet, 30 m...",61233,Class I,107624,CDER,https://www.accessdata.fda.gov/scripts/ires/?P...
82909,1.641527e+06,"Physicians Total Care, Inc",Drugs,Class I,Terminated,FL,Tulsa,Oklahoma,United States,2012-06-18,Labeling: Label mix-up; Bottles labeled to con...,"Morphine Sulfate Immediate Release tablet, 30 ...",61233,Class I,107625,CDER,https://www.accessdata.fda.gov/scripts/ires/?P...
82998,2.126677e+06,"GE Healthcare, LLC",Devices,Class I,Terminated,Nationwide Distribution - including the states...,Waukesha,Wisconsin,United States,2012-06-17,GE Healthcare has recently become aware of a p...,"GE Healthcare, Aestiva/5 7900 SmartVent, anest...",61639,Class I,108604,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...
83062,1.314492e+06,Baxter Healthcare Corporation,Devices,Class I,Terminated,Worldwide Distribution - USA Nationwide includ...,Medina,New York,United States,2012-06-13,Recall expansion; the infusion pumps have the ...,"Sigma Spectrum VOLUMETRIC INFUSION PUMP, with ...",61355,Class I,107879,CDRH,https://www.accessdata.fda.gov/scripts/ires/?P...

## Clean firm names for preprocessing

In [4]:
terms = prepare_default_terms()
basename = lambda x: custom_basename(x, terms, middle = True)
for i in range(2):
    for _ in range(3):
        recalls_medc1.loc[:, 'recalling_firm_name'] = \
            recalls_medc1.recalling_firm_name.map(basename)
    recalls_medc1.loc[:, 'recalling_firm_name'] = (
        recalls_medc1.recalling_firm_name.str.lower()
        .str.replace(r"\/|\.", ' ', regex = True)
        .str.replace(r'[^\w\s\-]', '', regex = True)
        .str.replace(r'\s+', ' ', regex = True)
        .str.replace(r'(?<=\b\w) (?=\w\b)', '', regex = True)
        .str.strip())

In [5]:
# deduplicate events per-firm in a 1-week period
colnames = ['event_id', 'recalling_firm_name', 'center_classification_date']
by = ['recalling_firm_name', pd.Grouper(key = 'center_classification_date', freq = 'W')]
recalls_events = recalls_medc1.loc[:, colnames].groupby(by).min().reset_index()
recalls_events

,recalling_firm_name,center_classification_date,event_id
0,4e brands north america,2020-10-11,86022
1,a-s medication solutions,2021-05-02,87436
2,aaa cosmetica,2020-09-13,86037
3,abbott,2018-05-20,79893
4,abbott diabetes care,2013-05-12,64876
...,...,...,...
1101,zimmer biomet,2017-02-12,75971
1102,zimmer biomet,2018-11-04,81127
1103,zions rx formulations services dba rx formuati...,2014-04-13,67080
1104,zydus pharmaceuticals usa,2013-08-04,65394
1105,zydus pharmaceuticals usa,2021-04-04,87364

In [6]:
recalls_firms = recalls_events.recalling_firm_name.drop_duplicates()
recalls_firms

0                                 4e brands north america
1                                a-s medication solutions
2                                           aaa cosmetica
3                                                  abbott
4                                    abbott diabetes care
                              ...
1098                                  zi xiu tang success
1099                                               zimmer
1101                                        zimmer biomet
1103    zions rx formulations services dba rx formuati...
1104                            zydus pharmaceuticals usa
Name: recalling_firm_name, Length: 633, dtype: object

## Infer matching stock symbols (LLM)

In [ ]:
fn_out = 'symbols_fda_recalls.csv'

def get_symbol(name, model = 'gpt-4o', ref = events.columns.tolist()):
    prompt = (f"{name}\nRETURN ONLY THE EXACT MATCH FOR THE BIOPHARMA/HEALTHCARE COMPANY'S STOCK "
              f"TICKER SYMBOL OR RETURN NOTHING IF THERE IS NO MATCH. DON'T GUESS.\n{name}")
    out = client.responses.create(
        model = model,
        input = prompt,
        temperature = 0
        ).output[0].content
    symbol = out[0].text.strip() if out else out
    symbol = symbol if symbol in ref else None
    # print(name, f'({symbol})')
    return symbol

with open(os.path.join(datadir, fn_out), 'w') as f:
    f.write('recalling_firm_name,Symbol\n')
    for ix in recalls_firms.index:
        name = recalls_firms.loc[ix]
        symbol = get_symbol(name)
        f.write(f'{name},{symbol}\n')

recalls_symbols = pd.read_csv(os.path.join(datadir, fn_out))
recalls_symbols = recalls_symbols.loc[~recalls_symbols.Symbol.isna()]
recalls_symbols.set_index('recalling_firm_name', inplace = True)
recalls_events = recalls_events.join(recalls_symbols, 'recalling_firm_name', 'inner')
recalls_events

          recalling_firm_name center_classification_date  event_id Symbol
3                      abbott                 2018-05-20     79893    ABT
4        abbott diabetes care                 2013-05-12     64876    ABT
5        abbott diabetes care                 2013-12-22     66886    ABT
6        abbott diabetes care                 2014-03-23     67472    ABT
7        abbott diabetes care                 2023-04-09     91756    ABT
...                       ...                        ...       ...    ...
1083  west pharma services il                 2019-02-03     81877    WST
1099                   zimmer                 2012-12-23     63683    ZBH
1100                   zimmer                 2015-06-14     71272    ZBH
1101            zimmer biomet                 2017-02-12     75971    ZBH
1102            zimmer biomet                 2018-11-04     81127    ZBH

[283 rows x 4 columns]

## Predict recall market impact dates

In [8]:
days_window = 90
recalls_events.loc[:, 'market_impact_date'] = pd.NaT
for ix in recalls_events.index:
    symbol = recalls_events.loc[ix].Symbol
    end = recalls_events.loc[ix].center_classification_date
    start = end - pd.Timedelta(days = days_window)
    events_i = events.loc[start : end, symbol]
    date_i = events_i.index[events_i == -1].max()
    recalls_events.loc[ix, 'market_impact_date'] = date_i
recalls_events = recalls_events.loc[~recalls_events.market_impact_date.isna()]
recalls_events.sort_values('market_impact_date', ascending = False, inplace = True)

C:\Users\ccrea\AppData\Local\Temp\ipykernel_29784\429766110.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recalls_events.sort_values('market_impact_date', ascending = False, inplace = True)

In [ ]:
# deduplicate events per-symbol in a 1-week period
by = ['Symbol', pd.Grouper(key = 'market_impact_date', freq = 'W')]
recalls_events = recalls_events.groupby(by).min().reset_index().set_index('event_id')
recalls_events.sort_values('market_impact_date', ascending = False, inplace = True)
recalls_events

,Symbol,market_impact_date,recalling_firm_name,center_classification_date
event_id,,,,
91506,BAX,2023-02-12,baxter healthcare,2023-02-26
91293,PHG,2022-10-16,philips respironics,2023-01-08
89970,VTRS,2022-03-06,mylan pharmaceuticals,2022-05-08
89276,PHG,2022-01-16,philips respironics,2022-01-23
88867,MRK,2021-11-07,merck sharp dohme,2021-11-07
88266,CAH,2021-08-08,cardinal health,2021-08-22
84886,BSX,2020-01-19,boston scientific,2020-03-29
82273,BDX,2019-04-21,becton dickinson,2019-06-30
82455,EW,2019-04-21,edwards lifesciences,2019-04-28
82291,ICUI,2019-03-10,icu medical,2019-04-21
81877,WST,2019-02-03,west pharma services il,2019-02-03
74843,OSUR,2016-07-03,orasure technologies,2016-08-21
71651,PODD,2015-08-16,insulet,2015-09-06
67922,FMS,2014-03-02,fresenius medical care holdings,2014-05-25
66441,ICUI,2014-02-23,icu medical,2014-03-16
66735,NEPH,2013-11-03,nephros,2013-12-22
64832,ICUI,2013-10-27,icu medical,2013-11-24
63364,ICUI,2013-07-21,icu medical,2013-08-04
64736,CAH,2013-03-24,cardinal health 200,2013-05-05
61355,BAX,2012-04-22,baxter healthcare,2012-06-17

## Compile ground-truth spillover network

In [10]:
days_window, edgelist = 7, list()
for ix in recalls_events.index:
    symbol_i = recalls_events.loc[ix].Symbol
    start = recalls_events.loc[ix].market_impact_date
    end = start + pd.Timedelta(days = days_window)
    events_i = events.loc[start : end]
    msk_j = ((events_i.abs() > 0).sum(0) > 0)
    symbols_j = [symbol_i] + events.columns[msk_j].tolist()
    edgelist.extend([(symbol_i, j) for j in symbols_j])
edgelist = list(set(edgelist))

In [11]:
outdir = os.path.join('..', 'DELAY', 'recalls-spillover-data')
refNetwork = pd.DataFrame(edgelist, columns = ['Gene1', 'Gene2'])
refNetwork.sort_values(['Gene1', 'Gene2'], inplace = True)
refNetwork.to_csv(os.path.join(outdir, 'refNetwork.csv'), index = False)
refNetwork

    Gene1 Gene2
157   BAX  ACHV
211   BAX  ADPT
128   BAX  ALGN
86    BAX  APLT
330   BAX  APRE
..    ...   ...
93    WST   OPK
259   WST  PMCB
258   WST  RNTX
150   WST  TECH
61    WST   WST

[385 rows x 2 columns]